source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'secureproperty_Example', :exclusive => true do
  pod 'SecureProperty', :path => '../'
end

target 'secureproperty_Tests', :exclusive => true do
  pod 'SecureProperty', :path => '../'

  
end
